#Basys3--logic_gates
set_property PACKAGE_PIN V17 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property PACKAGE_PIN V16 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property PACKAGE_PIN U16 [get_ports f[0]]
set_property IOSTANDARD LVCMOS33 [get_ports f[0]]
set_property PACKAGE_PIN E19 [get_ports f[1]]
set_property IOSTANDARD LVCMOS33 [get_ports f[1]]
set_property PACKAGE_PIN U19 [get_ports f[2]]
set_property IOSTANDARD LVCMOS33 [get_ports f[2]]
set_property PACKAGE_PIN V19 [get_ports f[3]]
set_property IOSTANDARD LVCMOS33 [get_ports f[3]]
set_property PACKAGE_PIN W18 [get_ports f[4]]
set_property IOSTANDARD LVCMOS33 [get_ports f[4]]
set_property PACKAGE_PIN U15 [get_ports f[5]]
set_property IOSTANDARD LVCMOS33 [get_ports f[5]]