set_property PACKAGE_PIN W4 [get_ports leddig[3]]
set_property IOSTANDARD LVCMOS33 [get_ports leddig[3]]
set_property PACKAGE_PIN V4 [get_ports leddig[2]]
set_property IOSTANDARD LVCMOS33 [get_ports leddig[2]]
set_property PACKAGE_PIN U4 [get_ports leddig[1]]
set_property IOSTANDARD LVCMOS33 [get_ports leddig[1]]
set_property PACKAGE_PIN U2 [get_ports leddig[0]]
set_property IOSTANDARD LVCMOS33 [get_ports leddig[0]]

set_property PACKAGE_PIN W7 [get_ports lednum[7]]
set_property IOSTANDARD LVCMOS33 [get_ports lednum[7]]
set_property PACKAGE_PIN W6 [get_ports lednum[6]]
set_property IOSTANDARD LVCMOS33 [get_ports lednum[6]]
set_property PACKAGE_PIN U8 [get_ports lednum[5]]
set_property IOSTANDARD LVCMOS33 [get_ports lednum[5]]
set_property PACKAGE_PIN V8 [get_ports lednum[4]]
set_property IOSTANDARD LVCMOS33 [get_ports lednum[4]]
set_property PACKAGE_PIN U5 [get_ports lednum[3]]
set_property IOSTANDARD LVCMOS33 [get_ports lednum[3]]
set_property PACKAGE_PIN V5 [get_ports lednum[2]]
set_property IOSTANDARD LVCMOS33 [get_ports lednum[2]]
set_property PACKAGE_PIN U7 [get_ports lednum[1]]
set_property IOSTANDARD LVCMOS33 [get_ports lednum[1]]
set_property PACKAGE_PIN V7 [get_ports lednum[0]]
set_property IOSTANDARD LVCMOS33 [get_ports lednum[0]]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} {get_ports clk}


set_property PACKAGE_PIN W19 [get_ports inc]
set_property IOSTANDARD LVCMOS33 [get_ports inc]
set_property PACKAGE_PIN T17 [get_ports dec]
set_property IOSTANDARD LVCMOS33 [get_ports dec]